var palavras = [
    "azulejo",
    "blitz",
    "crespo",
    "cripta",
    "duplex",
    "girar",
    "hifen",
    "indigno",
    "intrigante",
    "jazz",
    "marfim",
    "onix",
    "quartzo",
    "quiz",
    "valsa",
    "vaporizar",
    "vertiginoso",
    "vortice",
    "apicultor",
    "auditor",
    "bartender",
    "chef",
    "coach",
    "desembargador",
    "embaixador",
    "juiz",
    "perito",
    "roteirizador",
    "alpaca",
    "bacalhau",
    "chinchila",
    "escaravelho",
    "hamster",
    "lhama",
    "ouriço",
    "pelicano",
    "percevejo",
    "rouxinol",
    "sanguessuga",
    "ampulheta",
    "anzol",
    "desfibrilador",
    "fantoche",
    "forceps",
    "freezer",
    "navalha",
    "jaleco",
    "nebulizador",
    "pendulo",
    "spray",
    "webcam",
    "xadrez",
    "zíper",
    "bergamota",
    "cranberry",
    "feijoa",
    "groselha",
    "kiwi",
    "pistache",
    "gamer",
    "dinossauro",
    "calopsita",
    "alura", 
    "oracle", 
    "challenge", 
    "logica", 
    "texugo", 
    "caxumba", 
    "caixao", 
    "letreiro", 
    "joaninha", 
    "dinheiro", 
    "javascript", 
    "html", 
    "github", 
    "linkedin",
    "css"
];

function palavraAleatoria() {
    palavraSecreta = palavras[Math.floor(Math.random() * palavras.length)].toUpperCase()
}


const letrasErradas = []
const letrasCorretas = [];